# Generated by Django 4.1.3 on 2022-12-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specie', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('birth_date', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('AMAZE', 'AMAZE'), ('excited', 'EXCITED'), ('glad', 'GLAD'), ('happy', 'HAPPY'), ('sad', 'SAD')], max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.post')),
                ('reacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user'),
        ),
        migrations.CreateModel(
            name='PetStorePurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user')),
                ('pet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.petstore')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=50)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.user')),
                ('adoption_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.adoptioncenter')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.pet')),
            ],
        ),
    ]
