# Generated by Django 4.1.3 on 2022-12-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(),
        ),
    ]
