# Generated by Django 4.1.3 on 2022-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_pet_current_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionorder',
            name='current_status',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('pending', 'PENDING'), ('rejected', 'REJECTED'), ('reverted', 'REVERTED')], default='pending', max_length=50),
        ),
    ]
