# Generated by Django 4.1.3 on 2022-12-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_adoptioncenter_created_at_adoptioncenter_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioncenter',
            name='password',
            field=models.CharField(default='123456', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='current_adoption_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.adoptioncenter'),
        ),
        migrations.AddField(
            model_name='petstore',
            name='password',
            field=models.CharField(default=123456, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.user'),
        ),
        migrations.AlterField(
            model_name='petstore',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
