# Generated by Django 4.1.3 on 2022-12-31 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_alter_adoptioncenter_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptioncenter',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='adoptioncenter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adoptioncenter',
            name='password',
        ),
        migrations.RemoveField(
            model_name='petstore',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='petstore',
            name='email',
        ),
        migrations.RemoveField(
            model_name='petstore',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='in_adoption_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.adoptioncenter'),
        ),
        migrations.AddField(
            model_name='user',
            name='in_pet_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.petstore'),
        ),
    ]
