# Generated by Django 4.1.3 on 2022-12-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_remove_adoptioncenter_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
