# Generated by Django 4.1.3 on 2022-12-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_remove_pet_current_adoption_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionorder',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='petstorepurchaseorder',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
